services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: hockey_database_user
      POSTGRES_PASSWORD: hockey_password
      POSTGRES_DB: hockey_database
    ports:
      - "5433:5432"
    volumes:
      - prefect_data:/var/lib/postgresql/data
    networks:
      - prefect_network

  prefect-server:
    image: prefecthq/prefect:2-latest
    command: prefect orion start --host 0.0.0.0
    environment:
      PREFECT_API_DATABASE_URL: postgresql+psycopg2://hockey_database_user:hockey_password@postgres:5432/hockey_database
    ports:
      - "4200:4200"
    depends_on:
      - postgres
    networks:
      - prefect_network

networks:
  prefect_network:
    driver: bridge

volumes:
  prefect_data:
